version: '3'

services:
  app:
    build: .
    container_name: gitops-app
    entrypoint: ./.docker/entrypoint.sh
    tty: true
    volumes:
      - .:/home/python/app
    ports:
      - 8000:8000
      - 8003:8000
    depends_on:
      - db
  db:
    build: .docker/postgres
    container_name: gitops-db
    tty: true
    volumes:
      - .docker/pgdata:/var/lib/postgresql/data
    environment:
      # - LC_ALL=pt_BR.UTF-8
      - POSTGRES_DB=gitops
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    container_name: gitops-redis
    expose:
      - 6379
  pgadmin:
    image: dpage/pgadmin4
    container_name: gitops-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@user.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
      - "9000:80"
    depends_on:
      - db