apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: gitopsserver
  newName: candidosouza/}/fc_gitops
  newTag: 9d2cb7a54e95f40da91deb5dc36cbc2578e43512
